// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/markwallsgrove/muzz_devops/src/models"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Database) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *Database) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMatches provides a mock function with given fields: ctx, currentUserId, gender, minAge, maxAge
func (_m *Database) FindMatches(ctx context.Context, currentUserId int, gender models.Gender, minAge int, maxAge int) ([]models.UserProfile, error) {
	ret := _m.Called(ctx, currentUserId, gender, minAge, maxAge)

	var r0 []models.UserProfile
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Gender, int, int) []models.UserProfile); ok {
		r0 = rf(ctx, currentUserId, gender, minAge, maxAge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserProfile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.Gender, int, int) error); ok {
		r1 = rf(ctx, currentUserId, gender, minAge, maxAge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSwipe provides a mock function with given fields: ctx, firstUserId, secondUserId
func (_m *Database) GetSwipe(ctx context.Context, firstUserId int, secondUserId int) (models.Swipe, error) {
	ret := _m.Called(ctx, firstUserId, secondUserId)

	var r0 models.Swipe
	if rf, ok := ret.Get(0).(func(context.Context, int, int) models.Swipe); ok {
		r0 = rf(ctx, firstUserId, secondUserId)
	} else {
		r0 = ret.Get(0).(models.Swipe)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, firstUserId, secondUserId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *Database) GetUser(ctx context.Context, id int) (models.User, error) {
	ret := _m.Called(ctx, id)

	var r0 models.User
	if rf, ok := ret.Get(0).(func(context.Context, int) models.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Swipe provides a mock function with given fields: ctx, firstUserId, secondUserId
func (_m *Database) Swipe(ctx context.Context, firstUserId int, secondUserId int) (models.Swipe, error) {
	ret := _m.Called(ctx, firstUserId, secondUserId)

	var r0 models.Swipe
	if rf, ok := ret.Get(0).(func(context.Context, int, int) models.Swipe); ok {
		r0 = rf(ctx, firstUserId, secondUserId)
	} else {
		r0 = ret.Get(0).(models.Swipe)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, firstUserId, secondUserId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDatabase interface {
	mock.TestingT
	Cleanup(func())
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDatabase(t mockConstructorTestingTNewDatabase) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
